apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: go-api-pgsql
  name: go-api-pgsql
spec:
  output:
    to:
      kind: ImageStreamTag
      name: golang-builder-is:latest
  resources: {}
  source:
    git:
      ref: main
      uri: https://github.com/giofontana/go-api-pgsql-tekton-pipeline.git
    contextDir: api-pgsql/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.13.4-ubi7
        namespace: openshift
    type: Docker