
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-with-buildah
spec:
  params:
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint
      type: string
      default: 'false'
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string  
      default: "overlay"        
  resources:
    outputs:
      - name: output-image
        type: image       
  workspaces:
    - name: source  
  steps:
  - name: create-imagestream
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** CREATE IMAGE STREAM ****"
        oc apply -f cicd/k8s/api/imagestream.yaml  
        
  - name: build
    command:
      - buildah
      - bud
      - '--tls-verify=$(params.TLSVERIFY)'
      - '--storage-driver=$(params.STORAGE_DRIVER)'
      - '--layers'
      - '-f'
      - Dockerfile
      - '-t'
      - $(resources.outputs.output-image.url)
      - .
    image: registry.redhat.io/rhel8/buildah
    resources: {}
    securityContext:
      privileged: true
    workingDir: /workspace/source 
    volumeMounts:
      - name: pipeline-cache
        mountPath: /var/lib/containers    

  - name: push-image-to-openshift
    command:
      - buildah
      - push
      - '--storage-driver=$(params.STORAGE_DRIVER)'
      - '--tls-verify=$(params.TLSVERIFY)'
      - $(resources.outputs.output-image.url)
      - 'docker://$(resources.outputs.output-image.url)'
    image: registry.redhat.io/rhel8/buildah
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
      - name: pipeline-cache
        mountPath: /var/lib/containers

  volumes:
    - name: pipeline-cache
      persistentVolumeClaim:
        claimName: pipeline-task-cache-pvc        