
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-in-dev
spec:      
  workspaces:
    - name: source  
  steps:

  - name: pgsql-secrets
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY POSTGRESQL SECRETS IN DEV ENV ****"
        oc apply -f cicd/k8s/pgsql/pgsql_secret.yaml --wait

  - name: pgsql-pvc
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY POSTGRESQL PVC IN DEV ENV ****"
        oc apply -f cicd/k8s/pgsql/pgsql_pvc.yaml --wait


  - name: pgsql-service
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY POSTGRESQL SERVICE IN DEV ENV ****"
        oc apply -f cicd/k8s/pgsql/pgsql_svc.yaml --wait

  - name: deploy-pgsql
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY POSTGRESQL IN DEV ENV ****"
        oc apply -f cicd/k8s/pgsql/pgsql_dc.yaml --wait

        echo "**** WAIT FOR PGSQL BE READY ****"
        pg_pod_ready=''; while [ -z "$pg_pod_ready" ]; do pg_pod_ready=$(oc get pods -l deploymentconfig=postgresql -n go-api-pgsql-dev --no-headers | grep '1/1'); echo "PG_SQL pod still not ready!"; sleep 2; done


  - name: deploy-api-pgsql
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY APP IN DEV ENV ****"
        oc apply -f cicd/k8s/api/deployment.yaml --wait

        echo "**** WAIT FOR API BE READY ****"
        api_pod_ready=''; while [ -z "$api_pod_ready" ]; do api_pod_ready=$(oc get pods -l deploymentconfig=go-api-pgsql -n go-api-pgsql-dev --no-headers | grep '1/1'); echo "API pod still not ready!"; sleep 2; done


  - name: api-pgsql-service
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY SERVICE IN DEV ENV ****"
        oc apply -f cicd/k8s/api/service.yaml --wait

  - name: api-pgsql-route
    image: quay.io/openshift/origin-cli:latest
    workingDir: /workspace/source  
    command: ["/bin/bash", "-c"]
    args:
      - |-
        echo "**** DEPLOY ROUTE IN DEV ENV ****"
        oc apply -f cicd/k8s/api/route.yaml --wait        